apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-dannydavidson-com
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: api-dannydavidson-com
  rules:
  - http:
      paths:
      - path: /neo-app/*
        backend:
          serviceName: neo-app
          servicePort: 80
